### ISSUE TITLE
END INFO sub-field not documented in VCF Header

### ISSUE THREAD

**Issue by cjw85** [ccagc/QDNAseq#120]
From the [source](https://github.com/ccagc/QDNAseq/blob/19b53dd5c4851f0a8a0e21f34ed1a3793058cb66/R/exportBins.R#L215), the output VCF header does not include a description of the END sub-field which is subsequently [written](https://github.com/ccagc/QDNAseq/blob/19b53dd5c4851f0a8a0e21f34ed1a3793058cb66/R/exportBins.R#L281C5-L282C5).

The VCF v4.2 specification does not mandate that headers are provided, but does strongly encourage (Section 1.2). I have been given reports that the omission leads to failures in some data ingress pipelines.

**Comment by HenrikBengtsson** [comment]
Thanks. I'm quite rusty on VCF these days.  Could please you give an example of what the VCF header looks like right now and what you'd expect it to look like?  Right now, it's not clear to me if adding a "description of the END sub-field" is a quick fix or something more complicated.

**Comment by cjw85** [comment]
The correct link to find the authoritative source on VCF specifications is https://samtools.github.io/hts-specs/

Adding the field should be a quick fix, see the code block linked above as [source](https://github.com/ccagc/QDNAseq/blob/19b53dd5c4851f0a8a0e21f34ed1a3793058cb66/R/exportBins.R#L215). A line equivalent to e.g. `##INFO=<ID=LOG2CNT,Number=1,Type=Float,Description="Log 2 count">',` needs to be added. I could send you a PR but I don't know what a correct description of the field would be.

**Comment by HenrikBengtsson** [comment]
Implemented. It is staged to be pushed to Bioc devel branch.
