### ISSUE TITLE
Sex chromosomes

### ISSUE THREAD

**Issue by J-NYS** [ccagc/QDNAseq#30]
Dear authors

I have e problem to get the sex chromosomes of a .bam file and use them to make a plot of all the chromosomes.

Please see the pictures below.
Thank you in advance

![image](https://cloud.githubusercontent.com/assets/18593153/14882218/c5271324-0d37-11e6-9abd-4711b3aad892.png)

![image](https://cloud.githubusercontent.com/assets/18593153/14882165/8092cbe0-0d37-11e6-8ace-4dc00048a5f3.png)

![image](https://cloud.githubusercontent.com/assets/18593153/14882181/95d05054-0d37-11e6-83dc-7722ddf0d8e0.png)

**Comment by ilarischeinin** [comment]
Can you please provide an example where the relationship between plots shown, and the code used to generate them is clear. Now I'm not really sure how they were made.

Also, can you provide the QDNAseq package version you are using.

(It doesn't directly affect this, but just by the way: Next Wednesday (4 May), Bioconductor 3.3. will be released, which will include QDNAseq 1.8.0.)

**Comment by J-NYS** [comment]
I use version 1.6.1 (next week I will download the new version).

There are certainly sex chromosomes present in the file.
`samtools view –cq 30 484_IonXpress_004_rawlib.bam Y`
`1892`
`samtools view –cq 30 484_IonXpress_004_rawlib.bam X`
`546653`

The only thing I do is read `library(QDNAseq)`,
define bins: `bins <- getBinAnnotations(binSize=15)`,
and read the .bam file `readCounts <- binReadCounts(bins, bamfiles=.bam')`
Then I try to visualize the sex chromosomes.

Picture below shows the relationship. (I hope you mean the noise plot)
![image](https://cloud.githubusercontent.com/assets/18593153/14910808/0968c820-0df1-11e6-81af-751c1903c6e8.png)

**Comment by ilarischeinin** [comment]
Thanks. I meant please provide the code that really generates the plots in your first post.

**Comment by J-NYS** [comment]
```
### R code from vignette source 'QDNAseq.Rnw' => MODIFIED
### Initiation
library(QDNAseq)
options("QDNAseq::verbose"=NA)
options(width=40)
bins <- getBinAnnotations(binSize=15)

### Reading File(s)
setwd("~/Fedora22_Windows10/CMG/QDNAseq")
readCounts <- binReadCounts(bins, bamfiles='484_IonXpress_004_rawlib.bam')
setwd("C:/Users/jens/OneDrive/Howest/Bio-Informatica-BaNaBa/Stage/CMG/QDNAseq/QDNAseq_Output-test")

### Sex chromosomes (eval = FALSE)
readCounts <- binReadCounts(getBinAnnotations(15))
readCounts <- applyFilters(readCounts)
readCounts <- estimateCorrection(readCounts)
readCounts <- applyFilters(readCounts, chromosomes=NA)
copyNumbers <- correctBins(readCounts)

### Rawprofile
png("rawprofile_484-004.png")
plot(readCounts, logTransform=FALSE, ylim=c(-50, 200))
highlightFilters(readCounts, logTransform=FALSE,
                 residual=TRUE, blacklist=TRUE)
dev.off()

readCountsFiltered <- applyFilters(readCounts,
                                   residual=TRUE, blacklist=TRUE)

### Isobar
png("isobar_484-004.png")
isobarPlot(readCountsFiltered)
dev.off()

readCountsFiltered <- estimateCorrection(readCountsFiltered)

### Noise
png("noise_484-004.png")
noisePlot(readCountsFiltered)
dev.off()

copyNumbers <- correctBins(readCountsFiltered)
copyNumbers
copyNumbersNormalized <- normalizeBins(copyNumbers)
copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)

### Profile
png("profile_484-004.png")
plot(copyNumbersSmooth)
dev.off()

### Export -> .txt/.igv/.bed
exportBins(copyNumbersSmooth, file="LGG150.txt")
exportBins(copyNumbersSmooth, file="484_IonXpress_004_rawlib.igv", format="igv")
exportBins(copyNumbersSmooth, file="484_IonXpress_004_rawlib.bed", format="bed")

copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt")
copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)

### Segments
png("segments_484-004.png")
plot(copyNumbersSegmented)
dev.off()

### Calls (CGHregions)
library(CGHregions)
copyNumbersCalled <- callBins(copyNumbersSegmented)
png("calls_484-004.png")
plot(copyNumbersCalled)
dev.off()
cgh <- makeCgh(copyNumbersCalled)
cgh
```

**Comment by ilarischeinin** [comment]
Thanks. I see it now. You've simply copy&pasted the vignette's sex chromosome section in the middle the example run script. As a result, some of your objects have the sex chromosomes included, and some don't. That's why also some of your plots have them, and some don't. Please try to pay attention to which object is used by each function.

**Comment by ilarischeinin** [comment]
Something like this should do it:

```{r}
### R code from vignette source 'QDNAseq.Rnw' => MODIFIED
### Initiation
library(QDNAseq)
bins <- getBinAnnotations(binSize=15)

### Reading File(s)
setwd("~/Fedora22_Windows10/CMG/QDNAseq")
readCounts <- binReadCounts(bins, bamfiles='484_IonXpress_004_rawlib.bam')
setwd("C:/Users/jens/OneDrive/Howest/Bio-Informatica-BaNaBa/Stage/CMG/QDNAseq/QDNAseq_Output-test")

### Rawprofile
png("rawprofile_484-004.png")
plot(readCounts, logTransform=FALSE, ylim=c(-50, 200))
highlightFilters(readCounts, logTransform=FALSE,
                 residual=TRUE, blacklist=TRUE)
dev.off()

readCounts <- applyFilters(readCounts)

### Isobar
png("isobar_484-004.png")
isobarPlot(readCounts)
dev.off()

readCounts <- estimateCorrection(readCounts)

### Noise
png("noise_484-004.png")
noisePlot(readCounts)
dev.off()

readCounts <- applyFilters(readCounts, chromosomes=NA)
copyNumbers <- correctBins(readCounts)
copyNumbers
copyNumbers <- normalizeBins(copyNumbers)
copyNumbers <- smoothOutlierBins(copyNumbers)

### Profile
png("profile_484-004.png")
plot(copyNumbers)
dev.off()

### Export -> .txt/.igv/.bed
exportBins(copyNumbers, file="LGG150.txt")
exportBins(copyNumbers, file="484_IonXpress_004_rawlib.igv", format="igv")
exportBins(copyNumbers, file="484_IonXpress_004_rawlib.bed", format="bed")

copyNumbers <- segmentBins(copyNumbers, transformFun="sqrt")
copyNumbers <- normalizeSegmentedBins(copyNumbers)

### Segments
png("segments_484-004.png")
plot(copyNumbers)
dev.off()

### Calls (CGHregions)
library(CGHregions)
copyNumbers <- callBins(copyNumbers)
png("calls_484-004.png")
plot(copyNumbers)
dev.off()
cgh <- makeCgh(copyNumbers)
ugh
```

**Comment by J-NYS** [comment]
Thank you very much.

**Comment by P4sm** [comment]
I don't understand how these sex chromosomes are interpreted. I have a male sample and I used these parameters

`bins <- getBinAnnotations(binSize=100)`

`readCounts <- binReadCounts(bins,bamfiles = bam_file)`

`readCounts <- applyFilters(readCounts)`

`readCounts <- estimateCorrection(readCounts)`
`readCounts <- applyFilters(readCounts, chromosomes=NA)`


`copyNumbers <- correctBins(readCounts)`
`copyNumbersNormalized <- normalizeBins(copyNumbers)`

`copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)`

`plot(copyNumbersSmooth)`

![image](https://user-images.githubusercontent.com/23518979/31012751-aaa35896-a51b-11e7-847b-e8f0dd7f3a44.png)

So the program must assume by default that the sample has two X chromosomes and perhaps two Y chromosomes as well, because their average log2 ratio is -1?

If I run it with `readCounts <- applyFilters(readCounts, chromosomes="Y")` the results make sense.

![image](https://user-images.githubusercontent.com/23518979/31012968-95a1434e-a51c-11e7-8f01-1c84bb17e930.png)

**Comment by daoud-sie** [comment]
QDNAseq does not calculate ratios. The copy number values are absolute read counts which are corrected and normalized to zero. The confusion comes from the Y-axis label, it says "log2 ratio" but should say "log2 counts" instead. I will correct this in the next version.

**Comment by ilarischeinin** [comment]
It actually used to say "counts", but was changed to "ratio". This was because the way the correction is applied changed to being a ratio of "observed count / expected count".

Regardless of the semantics, what you're seeing in the plot isn't to say that zero means "normal".

**Comment by P4sm** [comment]
Ok, thank you. So regarding my original question: QDNAseq assumes that the sample has got two pairs of both X and Y chromosomes, just like every non-sex chromosome (although this is of course not normal, a male has one X chromosome and one Y chromosome). That is why the sex chromosomes have lower "log2 ratio". Have I understood correctly?

**Comment by P4sm** [comment]
And then QDNAseq identifies them both as deletions.

![image](https://user-images.githubusercontent.com/23518979/31013891-de099c54-a520-11e7-8bc9-e71bd39e7c67.png)

**Comment by ilarischeinin** [comment]
Kind of, but to be exact, QDNAseq doesn't really make any assumptions here. It simply shows you the data, which comes from your sequencer. And what you're seeing here is the fact that your sequencer encounters molecules originating from the sex chromosomes half as often as for other chromosomes.

The above was in response to the first one of your messages after my previous reply, and refers to other steps besides calling.

The calling step indeed does work in reference to other chromosomes. There are multiple approaches to dealing with the fact that the "normal" copy number varies between chromosomes, and QDNAseq doesn't really make this choice for you.

**Comment by P4sm** [comment]
Oh yes, it makes sense. I think QDNAseq works fine, but those sex chromosomes are a real pain, because discarding them changes the results.
