### ISSUE TITLE
Generating bin annotations for chrX..

### ISSUE THREAD

**Issue by johali** [ccagc/QDNAseq#31]
Dear authors, 

Im trying to annotate bins on chrX. Ive run the code accordingly to what is described in the documentation in "Generating bin annotations". Im using my own set of bam-files from the Swedish population (only females). 

When I run:
> applyFilters(ctrl, residual=FALSE, blacklist=FALSE, mappability=FALSE, bases=FALSE, chromosomes=c("Y"))

I get an error:
Error in aggregate.data.frame(as.data.frame(x), ...) : 
  no rows to aggregate
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

The ctrl-object seems ok to me. There is for sure readcounts from the bam-files and Ive run all the previous steps as described in the manual.
#####################################
> ctrl
QDNAseqReadCounts (storageMode: lockedEnvironment)
assayData: 206391 features, 63 samples 
  element names: counts 
protocolData: none
phenoData
  sampleNames: K19328N_wgs_subsampled K19353N_wgs_subsampled ...
    K37163N_wgs_subsampled (63 total)
  varLabels: name total.reads used.reads expected.variance
  varMetadata: labelDescription
featureData
  featureNames: 1:1-15000 1:15001-30000 ... Y:59370001-59373566 (206391
    total)
  fvarLabels: chromosome start ... blacklist (7 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation:  
#####################################

Any suggestions are welcome!

best regards, 

// Johan

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux release 6.7 (Carbon)

locale:
[1] C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg19_1.4.0 BSgenome_1.36.3                  
 [3] rtracklayer_1.28.10               Biostrings_2.36.4                
 [5] XVector_0.8.0                     GenomicRanges_1.20.8             
 [7] GenomeInfoDb_1.4.3                IRanges_2.2.9                    
 [9] S4Vectors_0.6.6                   Biobase_2.28.0                   
[11] BiocGenerics_0.14.0               QDNAseq_1.7.5                    

loaded via a namespace (and not attached):
 [1] DNAcopy_1.42.0          zlibbioc_1.14.0         GenomicAlignments_1.4.2
 [4] BiocParallel_1.2.22     impute_1.42.0           tools_3.2.2            
 [7] CGHcall_2.30.0          R.oo_1.20.0             marray_1.46.0          
[10] lambda.r_1.1.7          futile.logger_1.4.1     matrixStats_0.50.2     
[13] CGHbase_1.28.0          R.utils_2.3.0           futile.options_1.0.0   
[16] bitops_1.0-6            RCurl_1.95-4.8          limma_3.24.15          
[19] R.methodsS3_1.7.1       Rsamtools_1.20.5        XML_3.98-1.4

**Comment by ilarischeinin** [comment]
Can you try running this just before `applyFilters()`:

```{r}
fData(ctrl)$residual <- 0
```

And then continue from `applyFilters()` as you were doing. Let me know if that solves it.

**Comment by johali** [comment]
Thank you, it worked.

**Comment by johali** [comment]
Hi again, it works now. I have another related question. The final output produces log2 ratios, with the purpose to highlight regions where the genome has changed from a normal state. The autosomal regions are diploid whereas chrX in men only have one copy. After normalizeSegmentedBins, entire X appears to have lost 1 copy as it is processed as diploid by QDNAseq. I would like to correct chrX as otherwise it will always appear as if 1 copy is deleted when in fact is not altered.

How would you go about doing this as flawless as possible? It seems a bit tricky as I have a couple of samples whith a mix of "normal", loss and high-grade amplifications in X (attached pic). Spontaneously, I could median adjust according to the regions that are "called" to have lost 1 copy? Any advice are appreciated.
<img width="1059" alt="screen shot 2016-05-16 at 10 29 26" src="https://cloud.githubusercontent.com/assets/13965596/15284391/46c1dab4-1b51-11e6-8281-682e171f15f0.png">

**Comment by JspSrs** [comment]
Hi,
More complicating is the presence of both PAR1 and 2, at the tips of the chromosome, resp. 2.6Mb and 0.8 Mb. These are diploid regions.
And depending on the chemistry and variation in the assay one will see PAR 3, 4 and 5 pop-up. These can be ignored, as that is almost theoretical and will appear as polymorphic regions due to their frequency.

Jasper

**Comment by johali** [comment]
hi again, a possible workaround: 

1) Run autosomal regions as described in the QDNAseq manual.
2) Run chrX separately as a single chromsome using men only as background samples. 
3) Combine the info from 1) and 2). 

I have attached a figure again from the same patient as exemplified above. 

**Top panel:** Autosomal CNVs using the bins from the QDNAseq paper. The reason is that the CallBins function generates errors in varying iterations using my own bins. I found a thread previously where this error was associated with too few samples being run simultaneously. This is not the case here as I have 30 samples + the sample of interest processed at the same time.

Error: Command CGHcall() returned the following error message:
Error in optim(bstart, CGHcall:::.totallik, nreg = nreg, posteriorprev = posterior0, : function cannot be evaluated at initial parameters
Please contact maintainer of package CGHcall: Mark van de Wiel <mark.vdwiel@vumc.nl>
Execution halted

**Second panel:** Autosomal CNVs and on chrX using the new bins. A hard cutoff was used in callBins as this breaks as described above. Therefore, some segments are "neutral". Notice the problems with chrX.

**Third panel:** Processing only chrX and no autosomal chromosomes yields a better profile, at least by eyeballing it.

**Bottom panel:** As "top panel" but the chrX calls from the third panel was used.

Comment on chrY, I didn't have a good reference set at hand to defined the bins for Y, therefore it's not included. 

<img width="1261" alt="screen shot 2016-05-17 at 21 48 39" src="https://cloud.githubusercontent.com/assets/13965596/15337076/0d256828-1c7a-11e6-8293-df74a2464145.png">
