### ISSUE TITLE
Error msg of applyFilters(.... chromosomes=NA)

### ISSUE THREAD

**Issue by jiading** [ccagc/QDNAseq#34]
I try to use QDNAseq by including sex chr.

Here is part of my code:

		bins$residual <- iterateResiduals(ctrl_file)
		bins$use <- bins$chromosome %in% as.character(1:22) & bins$bases > 0
		readCounts <- binReadCounts(bins, bamfiles=InputFile)
		readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
		readCounts <- estimateCorrection(readCounts, control=loess.control(surface="direct"))
		readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE, chromosomes=NA)	# includes both X & Y

		copyNumbers <- correctBins(readCounts)

		copyNumbersNormalized <- normalizeBins(copyNumbers)
		copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)

Then I got such error msg:
> readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
12,397	total bins
11,537	of which in selected chromosomes
10,829	of which with reference sequence
 9,711	final bins
> readCounts <- estimateCorrection(readCounts, control=loess.control(surface="direct"))
Calculating correction for GC content and mappability:
    Calculating fit for sample GC030283-AR003-160314_nipt_CC-MT066-675-freeze1_4.gatk.freeze1.4 (1 of 1) ...
Done.
> readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE, chromosomes=NA)# includes both X & Y
12,397	total bins
12,397	of which in selected chromosomes
11,548	of which with reference sequence
    NA	final bins
> #fData(readCounts)$use <- fData(readCounts)$use & !is.na(rowMeans(assayDataElement(readCounts, "fit")))
> copyNumbers <- correctBins(readCounts)
Note: Filtering out additional 0 bins due to missing values.
> 
> copyNumbersNormalized <- normalizeBins(copyNumbers)
Applying median normalization ...
> copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
Smoothing outliers ...Error in copynumber2[condition, ] <- copynumber : 
  NAs are not allowed in subscripted assignments
In addition: Warning messages:
1: In CNA(copynumber[condition, , drop = FALSE], chrom = fData[condition,  :
  markers with missing chrom and/or maploc removed

2: In data.row.names(row.names, rowsi, i) :
  some row.names duplicated: 9713,9714,9715,9717,9718,9719,9720,9721,9722,9723,9724,9726,9727,9728,9731,9732,9733,9734,9736,9737,9739,9740,9741,9742,9743,9744,9745,9749,9750,9751,9753,9754,9755,9756,9758,9

**Comment by ilarischeinin** [comment]
Does that happen when you use the provided bin annotations or only with your custom ones?

**Comment by jiading** [comment]
Hi @ilarischeinin 

Let me first briefly what I want to do.

I have single cell data for control and case to call CNV. There is only 1 case but 4 controls which I think I will separate them into female control and male control to call CNV more accurately.

I will try with Binsize from 10k to 1M, because I don't know what's the best binsize for my data. I create bins by following command. (please find them in the end of the post). To my understanding, I am using provided bin annotations.	

I used wgEncodeCrgMapabilityAlign50mer, I also see there are other mapability files with different kmer size. I assume 50mer is Ok, but I actually have no idea how it will influence my output.  Do you happen to know anything about it?

Another thing confuses me is that, I thought, QDNAseq can run without controls, since we have annotation about bins. Am I wrong here?


## create Bins
bins <- createBins(bsgenome=BSgenome.Hsapiens.UCSC.hg19, binSize=BINSIZE[i])
	bins$mappability <- calculateMappability(bins,bigWigFile='/uz/data/avalok/symbiosys/raw/bio/resources/species/homo_sapiens/hg19/wgEncodeMapability/wgEncodeCrgMapabilityAlign50mer.bigWig',bigWigAverageOverBed='~/Anno/bigWigAverageOverBed' )
	bins$blacklist <- calculateBlacklist(bins,bedFiles=c('~/Anno/wgEncodeDacMapabilityConsensusExcludable.bed','~/Anno/wgEncodeDukeMapabilityRegionsExcludable.bed'))


	## create controls
	ctrl_female <- binReadCounts(bins, bamfiles=bamFile[c(17,19)])
	fData(ctrl_female)$residual <- 0
	ctrl_female <- applyFilters(ctrl_female, residual=FALSE, blacklist=FALSE, mappability=FALSE, bases=FALSE, chromosomes=c("Y"))    

# ---->  here I exclude Y, because it's female case. If it's male case, I create control by adding (..... chromosomes=NA)
	fData(ctrl_male)$residual <- 0
	ctrl_male <- applyFilters(ctrl_male, residual=FALSE, blacklist=FALSE, mappability=FALSE, bases=FALSE, chromosomes=NA)

## add residual & use columns into bins
		bins$residual <- iterateResiduals(ctrl_file)
		bins$use <- bins$chromosome %in% as.character(1:22) & bins$bases > 0
# -----> I assume, I shall not including "X" & "Y" here. Or maybe I am wrong? 

## call CNV
		readCounts <- binReadCounts(bins, bamfiles=InputFile)
		readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
		readCounts <- estimateCorrection(readCounts, control=loess.control(surface="direct"))
		readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE, chromosomes=NA)	# includes both X & Y
#		fData(readCounts)$use <- fData(readCounts)$use & !is.na(rowMeans(assayDataElement(readCounts, "fit")))
		copyNumbers <- correctBins(readCounts)

		copyNumbersNormalized <- normalizeBins(copyNumbers)
		copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
# ---> here, the ERROR occurs.
#		plot(copyNumbersSmooth)
		copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt")
		copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
		copyNumbersCalled <- callBins(copyNumbersSegmented)

**Comment by ilarischeinin** [comment]
I think you've misunderstood something. If you're using hg19, there is no need to create the bins (= "bin annotations") yourself, as long as you're happy with the sizes and read lengths provided. They include read length 50bp and bin sizes of 1, 5, 10, 15, 30, 50, 100, 500, and 1000 kbp. Just fetch them with, e.g.:

```{r}
bins <- getBinAnnotations(15)
```

To clarify, there is no need to use `createBins()` in that case.

> I used wgEncodeCrgMapabilityAlign50mer, I also see there are other mapability files with different kmer size.

You should use the one that matches the read length of your experiment.

> Another thing confuses me is that, I thought, QDNAseq can run without controls, since we have annotation about bins.

Exactly, QDNAseq is meant to be used without controls.

As for the error, I think it might be resolved with any one of these options:
1. using the provided bin annotations (`getBinAnnotations()`)
2. specifying `blacklist=FALSE` to `applyFilters()`
3. using QDNAseq version 1.9.1 (once Bioconductor has picked that up, or by installing from GitHub with `devtools::install_github("ccagc/QDNAseq")`.

My first recommendation is option 1, then 2, and then 3.

**Comment by jiading** [comment]
The reasons I want to try my own control are:

1, single cell data could be very noisy, maybe our own control is more close to the reality. Although I am not sure about it.
2, by building sex specific control, maybe it will be more sensitive to detect sex CNVs.

Have you made comparison? Or Let's say which annotation would you prefer?

I am in favor of using "blacklist = TRUE",  I hope that's not the reason of ERROR.

**Comment by ilarischeinin** [comment]
There is still no need to create new bin annotations. If you want to use your own samples for the `residual`, you can just override the one from the ready-made bin annotations.

And if you are using your own bin annotations, and haven't added a blacklist with `calculateBlacklist()`, that is most likely the reason for the error.
