### ISSUE TITLE
compareToReference Error

### ISSUE THREAD

**Issue by jiading** [ccagc/QDNAseq#37]
I have 4 samples as control, 1 as case.
I would like to use the control set to removed the bias for my 1 case sample, in additional to ref-free approach (GC & mappability).
I've tried.

		bins <- getBinAnnotations(binSize=15)
		readCounts <- binReadCounts(bins, bamfiles=bamFile[1])
		ctrl_all <- binReadCounts(bins, bamfiles=bamFile[2:5])

		readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
		ctrl_all <- applyFilters(ctrl_all,residual=TRUE, blacklist=TRUE)

		readCounts <- estimateCorrection(readCounts)
		copyNumbers <- correctBins(readCounts)
		copyNumbersNormalized <- normalizeBins(copyNumbers)
		copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)

 compare <- compareToReference(copyNumbersSmooth,ctrl_all)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘compareToReference’ for signature ‘"QDNAseqCopyNumbers", "QDNAseqReadCounts"’

		copyNumbersSegmented <- segmentBins(compare, transformFun="sqrt")
		copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
		copyNumbersCalled <- callBins(copyNumbersSegmented)

I guess is because I am trying to compare two different types of objects.
Does it mean that I have to use "applyFilter -> estimateCorrection -> correctBins -> normalizeBin -> smoothOutlierBins for  both control and case,  then "compareToReference" , and run "segmentBins" ect in the final step?

Thanks.

**Comment by ilarischeinin** [comment]
Please read the man page for `compareToReference()`. You need to have both your cases and controls in the same `readCounts` object. The `references` parameter specifies a numerical index for the reference sample to be used for each case. Since you have multiple references you want to use for a single case, you first need to use `poolRuns()` to combine them.

**Comment by jiading** [comment]
Just to be sure, I shall first "normalizeBins()" to both case and control before using "compareToReference()", right?

**Comment by ilarischeinin** [comment]
I'm not sure if it actually makes any difference, but at least it does no harm. You should probably (re-)run `normalizeBins()` after `compareToRerence()` though.

**Comment by jiading** [comment]
I don't think I actually need to use "poolRuns()", as I am import all reference bam files all at once by "ctrl_all <- binReadCounts(bins, bamfiles=bamFile[2:5])"

Or ?

**Comment by ilarischeinin** [comment]
You do. You need to do something along the lines of:

```r
bins <- getBinAnnotations(binSize=15)
readCounts <- binReadCounts(bins, bamfiles=bamFile)
readCounts <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
readCounts <- estimateCorrection(readCounts)
copyNumbers <- correctBins(readCounts)
copyNumbers <- normalizeBins(copyNumbers) # maybe not needed
copyNumbers <- poolRuns(copyNumbers, c("case", "ctrl", "ctrl", "ctrl", "ctrl"))
copyNumbers <- normalizeBins(copyNumbers) # maybe not needed
copyNumbers <- compareToReference(copyNumbers, c(2, FALSE))

copyNumbersNormalized <- normalizeBins(copyNumbers)
copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
copyNumbersSegmented <- segmentBins(copyNumbersSmooth, transformFun="sqrt")
copyNumbersSegmented <- normalizeSegmentedBins(copyNumbersSegmented)
copyNumbersCalled <- callBins(copyNumbersSegmented)
```

But you'll probably need `method="cutoff"` for `callBins()`.
