### ISSUE TITLE
number of reads in the bins

### ISSUE THREAD

**Issue by jiading** [ccagc/QDNAseq#38]
I am wondering how QDNAseq count the number of total reads in the bins.

I have a single-end 51bp fastq file, and mapped with bwa mem & removed duplicates. (to simplify, I call it t1)
Meanwhile, I clipped off the beginning of each reads of the same file, the length of reads drop to 32bp, I do the same with mapping and remove duplicates. (I call it t2)

I use samtools flagstats to check both bam files.

----> t1: (51bp)
9523780 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
9523753 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

-------> t2: (32bp)
17392161 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
10208727 + 0 mapped (58.70% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

From flagstat,  t2 (32bp) has higher mapping percentage than t1(51bp), But 
 QDNAseq figures tell me the opposite.

![1](https://cloud.githubusercontent.com/assets/474797/16523214/73fa2160-3fa2-11e6-8849-f627730f8f6d.png)

The top figure is from t1(51bp reads), figure below is from t2(32bp reads).

I don't quite understand why QDNAseq says t1 has 7972254 reads, while t2 has only 6965162. 
T2 has higher number of mapped reads than t1.

I wonder how QDNAseq count reads in the bin?

**Comment by ilarischeinin** [comment]
`binReadCounts()` has an argument `minMapq`, which specifies the minimum read mapping quality. By default it's 37, and could explain the difference.

QDNAseq also only counts reads that map to the chromosomes that are included in the bin annotations that were used. For the proved bin annotations that is 1-22, X, and Y.
