### ISSUE TITLE
Error in optim(bstart, CGHcall:::.totallik, nreg = nreg, posteriorprev = posterior0,  :

### ISSUE THREAD

**Issue by dakl** [ccagc/QDNAseq#4]
For some samples, I get this when running `callBins()` (including upstream code for completion): 

```
> bins <- getBinAnnotations(binSize=15)
> readCounts <- binReadCounts(bins, bamfiles=opts$bam)
> readCountsFiltered <- applyFilters(readCounts,residual=TRUE, blacklist=TRUE)
> readCountsFiltered <- estimateCorrection(readCountsFiltered)
> copyNumbers <- correctBins(readCountsFiltered)
> copyNumbersNormalized <- normalizeBins(copyNumbers)
> copyNumbersSmooth <- smoothOutlierBins(copyNumbersNormalized)
> copyNumbersSegmented <- segmentBins(copyNumbersSmooth)
> copyNumbersSegmentedNormalized <- normalizeSegmentedBins(copyNumbersSegmented)
> plot(copyNumbersSegmentedNormalized)
> copyNumbersCalled <- callBins(copyNumbersSegmentedNormalized)

> copyNumbersCalled <- callBins(copyNumbersSegmentedNormalized)
EM algorithm started ... 

[1] "Total number of segments present in the data: 38"
[1] "Number of segments used for fitting the model: 31"
258384413403405138102.3393353330228883210.1230.73933533111539697210.1851
Calling iteration1:

Error in optim(bstart, CGHcall:::.totallik, nreg = nreg, posteriorprev = posterior0,  : 
  function cannot be evaluated at initial parameters
```

I'm also attaching the plot that I generate. Might be useful for debugging. 

![screenshot 2014-10-24 10 15 18](https://cloud.githubusercontent.com/assets/17823/4766814/1ee6a432-5b56-11e4-8880-8e59ad7d5fbd.png)

**Comment by ilarischeinin** [comment]
Since version 1.2.2/1.3.3 QDNAseq gives a smarter error message explaining that the error is coming from CGHcall.

**Comment by jiading** [comment]
@ilarischeinin 

same error msg happens to me.
I have 16 non-tumor samples. They were taken from different individuals, so totally unrelated. I am not sure if I can combine them.

Any suggestions?

Thanks.

**Comment by ilarischeinin** [comment]
As has been said, this error message comes from package CGHcall, so there are two options:
1. Contact the maintainer of CGHcall about the error, or
2. Instead of using CGHcall, tell `callBins()` use cutoffs by specifying `method="cutoff"`.
