### ISSUE TITLE
QDNAseq support for .cram files

### ISSUE THREAD

**Issue by matthdsm** [ccagc/QDNAseq#43]
Hi,

Is there any support for .cram files (compressed bam) on the roadmap? Or is there a workaround that doesn't require file conversion?

Thanks
M

**Comment by ilarischeinin** [comment]
QDNAseq reads bam files via [Rsamtools](http://bioconductor.org/packages/release/bioc/html/Rsamtools.html), which is another package in the Bioconductor suite. If that package adds support for cram files, QDNAseq will also be able to read them, with either no or with very minimal changes.

Of course it could be possible to implement the feature directly in QDNAseq, but a Bioconductor-wide support would probably be the best option.
