### ISSUE TITLE
How to extract copy number aberrations

### ISSUE THREAD

**Issue by ghost** [ccagc/QDNAseq#55]
Hello

I would like to extract the data QDNAseq uses to make the copy number plots. I used the exportBins function to output the segmented data for copy number gains and losses. To do that, I used the following line of code, 

exportBins(copyNumbersCalled, file=paste0(bambase,"_export_bins_calls.tsv"), format="tsv", type="calls")

I think that the output I got is not correct because it doesn't correspond to the plot QDNAseq generates. The output contains columns for the sample name and then values -1022 and 0. I need to extract all the chromosomal fragments which contain the aberrant CN. If I select for 0 I only get chromosomal regions with logR >0. How can I also access logR <0? Is there a way to do that or is there something wrong with the code?

Furthermore, when I used the line below the segments the code returned were not consistent with the plot the package made. I can provide examples if needed.

exportBins(copyNumbersCalled, file=paste0(bambase,".seg"), format="seg", type="calls")

Please let me know what you think. 

Thank you, 

Katerina

**Comment by daoud-sie** [comment]
Hi Katerina,

By default the function exportBins log transforms the data. This makes sense for copynumber and segment data, but not for call (which is categorical data). At the moment exportBins does not automatically switch the log transformation, so you have to explicitly state “logTransform=FALSE”:

exportBins(copyNumbersCalled, file=paste0(bambase,"_export_bins_calls.tsv"), format="tsv", type="calls", logTransform=FALSE)

Furthermore, I’m not sure what you mean by inconsistent, could you provide an example?

Grtz,

Daoud

**Comment by AikaterinaChatzipli** [comment]
Hi Daoud,

Many thanks for your email. logTransform=FALSE worked and gave me the data
I needed.

I need to ask you something different I noticed on the copy number plots. I
see that QDNAseq comes up with copy number changes which I cannot see when
looking at the coverage. I attach a file where I plotted the coverage of a
sample at the top and QDNAseq output at the bottom. I also highlighted
gains and losses in red and blue, respectively. I wonder if the the small
copy number changes are real or not as I cannot really explain them. Have
you seen this before and do you think they are real? I have the feeling
they are artefacts and I will need to filter them out of my plots. Could
you please tell me what you think?

Many thanks,

Katerina

Στις Παρ, 10 Αυγ 2018 στις 4:56 μ.μ., ο/η Daoud <notifications@github.com>
έγραψε:

**Comment by HenrikBengtsson** [comment]
This is fixed in **QDNAseq** (>= 1.29.3) that I will push to Bioconductor in the next few days, i.e. now `logTransform` is ignored (not used) if `type = "calls"`.  See also #88.
