### ISSUE TITLE
hg38 compatibility

### ISSUE THREAD

**Issue by sxv** [ccagc/QDNAseq#57]
Hi,

Will this package work with bams aligned to hg38? Any issues to be aware of?

Thanks,
Sujay

**Comment by nikleotide** [comment]
Hello Sujay,
Were you able to work around using hg38?

Thanks.
H.

**Comment by lbeltrame** [comment]
I made my own bins from 1000G fastq files aligned against hg38. That was time consuming but the only option I could see. It seems to work (currently still evaluating).

**Comment by HenrikBengtsson** [comment]
Further discussion on this topic has been moved to https://github.com/ccagc/QDNAseq/issues/59.
