### ISSUE TITLE
Problems with exportVCF function

### ISSUE THREAD

**Issue by LanyingWei** [ccagc/QDNAseq#62]
Hi, 

Thank you for this tool, I found that the blacklist is really helpful:) And here is a little suggestion from my side: it seems that exportVCF combines CNVs from faraway into a large CNV, which is cased by 	code sel <- d[,4] != 0 & !is.na(d[,4]) in this function, I changed it to sel <- !is.na(d[,4]) and did some small modifications, then the result looks normal (see attached pic)...another thing is that it also reports CNV which covers a large proportion of bins in blacklist, I did some filtration based on the proportion, so maybe it will be better if this filtration is performed~

Best, 
Lanying

![Screenshot from 2019-04-11 13-39-49](https://user-images.githubusercontent.com/49517206/55946924-d65a7380-5c4d-11e9-9cdb-1cd163126703.png)

**Comment by RoelKluin** [comment]
Should be fixed with https://github.com/ccagc/QDNAseq/pull/90

**Comment by HenrikBengtsson** [comment]
As mentioned in the closely related Issue #87, this has been [fixed](https://github.com/ccagc/QDNAseq/actions/runs/1305257037) for the next release to become QDNAseq 1.29.3. You can try it already now by:
 
```shell
remotes::install_github("ccagc/QDNAseq", ref = "develop")
```

Thanks again for reporting.
