### ISSUE TITLE
CLEANUP: Retire AWS S3 annotation data in favor of QDNAseq.{{genome}} packages

### ISSUE THREAD

**Issue by HenrikBengtsson** [ccagc/QDNAseq#67]
The (`QDNAseq::getBinAnnotations(genome = "hg19")`](https://github.com/ccagc/QDNAseq/blob/master/R/getBinAnnotations.R) function will:

1. use the annotation available in the Bioc [QDNAseq.hg19](http://bioconductor.org/packages/release/data/experiment/html/QDNAseq.hg19.html) package **iff installed**, otherwise
2. It will download individual RDS files over HTTP from an AWS S3 server, e.g. http://qdnaseq-ireland.s3.amazonaws.com/QDNAseq.hg19.15kbp.SR50.rds.

The 2nd approach originates from the early days of QDNAseq and is unstable, e.g. the AWS S3 server might be discontinued.  The 1st approach is more sound and long-term sustainable (e.g. the QDNAseq.hg19 package is archived on Bioconductor forever). 

Another problem with the above is that you have to know about the QDNAseq.hg19 package and that you should install it.  Since QDNAseq.hg19 and QDNAseq.mm10 are both on Bioconductor, I'd like to propose retiring the AWS S3 approach and replace it with an informative error referring to the expected `QDNAseq.{{genome}}` package.

**Comment by ilarischeinin** [comment]
I support this, but would like to explicitly mention one use case scenario. The new function should still support (down)loading the bin annotations from a local file path/remote URL, in case people generate their own bin annotations. But the default AWS S3 URL could (and should) be retired with an informative error message.

**Comment by HenrikBengtsson** [comment]
The following has been changed in QDNAseq 1.21.3-9000 (develop branch for now - to be pushed to Bioconductor [devel](https://bioconductor.org/packages/devel/bioc/html/QDNAseq.html) in a couple of days):
```
SIGNIFICANT CHANGES:

 * Bin annotation data files are no longer downloaded automatically. They
   are instead part of Bioconductor annotation packages QDNAseq.hg19 and
   QDNAseq.mm10, which needs to be installed by the user.  If not installed,
   an error is now produced.  The reason for this change, is that the
   QDNAseq maintainers will no longer hosts QDNAseq bin annotation files
   online (in the cloud).
```

**Comment by ilarischeinin** [comment]
Nice work. Thank you, @HenrikBengtsson!
