### ISSUE TITLE
Why i am getting error when writing a function for “optim”?

### ISSUE THREAD

**Issue by optimsari** [ccagc/QDNAseq#7]
I have three directories where there is inside each of them 5 files.each file is a matrix lines 500 and columns 300. I want to perform an optimization using values from three corresponding pixels.Finally I get a matrix of lines 500 and columns 300 for each parameter in my equation:

       y=(ax1+bx2+c)^2+d 
reproducible example:

         dat1 <- array(1:60, c(3,5,4));dat2 <- array(rnorm(60), c(3,5,4)); 
        dat3 <-array(rnorm(60), c(3,5,4)) 
 reorder dimensions

          dat1 <- aperm(dat1, c(3,1,2));dat2 <- aperm(dat2, c(3,1,2)); 
            dat3 <- aperm(dat3, c(3,1,2)) 
make array a matrix

          dat1a <- dat1  ; dim(dat1a) <- c(dim(dat1)[1],prod(dim(dat1)[2:3])) 
         dat2a <- dat2;  dim(dat2a) <- c(dim(dat2)[1],prod(dim(dat2)[2:3])) 
          dat3a <- dat3 ; dim(dat3a) <- c(dim(dat3)[1],prod(dim(dat3)[2:3])) 
fun

         fun=function(x1,x2, y) { 
             keep <- !(is.na(x1) | is.na(x2)| is.na(y)) 
                 if (sum(keep) > 2) { #less than 3 non-NA values? 
                      FUN=function(p){sum((y[keep] -  
                             (p[1]*x1[keep]+p[2]*x2[keep]+p[3])^p[4]+p[5])^2)}

                     res <- optim(par=c(1,2,3,4,5),FUN)$par[,1] 
               } else { 
               res <- c(NA, NA,NA,NA,NA)#five parameters 
                  } 
                   res 
                 } 
results:

              res <- mapply(fun, x1=as.data.frame(dat1a), x2=as.data.frame(dat2a),   y=as.data.frame(dat3a)) 
 Error in optim(rep(NA, 5), temp) : non-finite value supplied by optim 
My Fun is not correct! Any idea please on how to correct my function?

**Comment by ilarischeinin** [comment]
I don't see how this is related to QDNAseq.
