### ISSUE TITLE
Bin annotation data: Sustainability and how to list available data?

### ISSUE THREAD

**Issue by HenrikBengtsson** [ccagc/QDNAseq#8]
The `QDNAseq.<genome>.<binSize>kbp.<type>.rds` bin annotation data files is provided via Amazon S3, cf. commit 1418d39.  A few questions/comments:

1. Except by trial and error, how can a user know for which genomes, bin sizes and types pre-built annotation data are available?  Maybe there is a way to enable file indexing on that S3 folder?

2. Would you mind considering "archiving" these in a [Bioconductor Annotation package](http://www.bioconductor.org/packages/release/data/annotation/), e.g. `QDNAseq.hg19`?  This way:
  - `QDNAseq` will/can live forever, even beyond a day when you move on and decide to drop the Amazon S3 account.  (_Anecdotal: I've had this issue myself over at Aroma Project where we hosted some scripts/annotation data on external servers which are now gone, because those labs have shut down/moved on. Unfortunately, we also lost some of the scripts/data along the way._)
  - With this available, one could use `QDNAseq.hg19` as the main source and have QDNAseq to fall back to external source (i.e. Amazon S3) for cases not available in the package.
  - It will be more clear to the end user for which genomes/organisms QDNAseq "support".

**Comment by ilarischeinin** [comment]
1. Trial and error indeed the only way at the moment (and hg19 is the only one supported).

2. I remember that when thinking how to set this up, I did consider Bioconductor Annotation packages as one option, but not sure why I did not use them. I'd imagine it was related to the fact that this is not only about which genomes to support, but also which bin sizes. i.e. which bin sizes would package `QDNAseq.hg19` include, or would each bin size (for each genome) be it's own package? Currently for hg19 we have 1, 5, 10, 15, 30, 50, 100, 500, and 1000 kbp. File sizes vary a lot, so while 1000 kbp is 59 KB, the 1 kbp one is 24 MB. All together they are 38 MB. On one hand it would seem unnecessary to require users to download all bin sizes for a genome they want to use, and on the other it would feel that making each genome/bin size combination its own package would result in too many packages cluttering Bioconductor. Not sure if the latter is really a valid point though.

Anyways, right now the S3 bucket is actually under my personal AWS account, so some other arrangement is indeed needed long term.

**Comment by daoud-sie** [comment]
I have asked Stef to find a place to host the bin annotations. Not sure what the status is. I will ask him next week when I'm back in the office. This should at least move the downloads from your personal S3 account.

I do like the idea of using the annotations package. Its probably not as easy as it sounds but I'm going look into it and see if we can implement it.


---- Ilari Scheinin wrote ----


  1.  Trial and error indeed the only way at the moment (and hg19 is the only one supported).

  2.  I remember that when thinking how to set this up, I did consider Bioconductor Annotation packages as one option, but not sure why I did not use them. I'd imagine it was related to the fact that this is not only about which genomes to support, but also which bin sizes. i.e. which bin sizes would package QDNAseq.hg19 include, or would each bin size (for each genome) be it's own package? Currently for hg19 we have 1, 5, 10, 15, 30, 50, 100, 500, and 1000 kbp. File sizes vary a lot, so while 1000 kbp is 59 KB, the 1 kbp one is 24 MB. All together they are 38 MB. On one hand it would seem unnecessary to require users to download all bin sizes for a genome they want to use, and on the other it would feel that making each genome/bin size combination its own package would result in too many packages cluttering Bioconductor. Not sure if the latter is really a valid point though.

Anyways, right now the S3 bucket is actually under my personal AWS account, so some other arrangement is indeed needed long term.

**Comment by HenrikBengtsson** [comment]
@ilarischeinin, for the current S3 folder, as a minimal-effort emulation of an index.html page, would you mind adding a `ls -l > index.html` file?

**Bioconductor annotation package**: 

* It made sense to not worry about an annotation package during the development phase of QDNAseq, but now when there is a stable release and a publication, it does make sense.  One could still allow for options to use "live" annotation data as today, e.g. for organisms under development or for custom annotation data provided by third-party groups (which is common in the microarray world). 

* I don't think you have to worry about the size (~38MB) of the annotation package.  Bioconductor hosts annotation packages that are 100's of MB large, even in the GB range.  Also, the installation "weight" of [QDNAseq](http://bioconductor.org/packages/release/bioc/html/QDNAseq.html) is much larger than this annotation data, cf. the packages required for [Rsamtools](http://bioconductor.org/packages/release/bioc/html/Rsamtools.html).  This is also going to be used by people that shuffles TB's of DNA-Seq data around.

* I would stick with the 1, 5, 10, 15, 30, 50, 100, 500, and 1000 kbp bins as suggested in the package/manuscript.

* I can imagine a very basic package structure where annotation data is available via `data(<var>, package="QDNAseq.hg19")` which `QDNAseq::getBinAnnotations()` can tie into.  The package would also be a natural place to store scripts, docs, log files from when the annotation data were built, although those details could be added after the first release if time is scarce. 

* The Bioconductor [Package Guidelines](http://master.bioconductor.org/developers/package-guidelines/#package-types) says: "Annotation packages are database-like packages that provide information linking identifiers (e.g., Entrez gene names or Affymetrix probe ids) to other information (e.g., chromosomal location, Gene Ontology category)." and "... annotation and experiment data packages are not required to conform to the space limitations of software packages. Developers wishing to contribute annotation or experiment data packages should seek [additional support](http://master.bioconductor.org/developers/package-submission/#support) associated with package submission."

* The next [Bioconductor release (3.0)](http://bioconductor.org/developers/release-schedule/) is coming up where **the freeze is on March 19**.  Unfortunately I have very little (=10^-16) time working on this until then.  Do you guys have time?  It would be great to get it in before that.  A quick message to the Bioc folks (maybe referencing this issue) would tell us if this is reasonable or not.

**Comment by ilarischeinin** [comment]
I added an [index](http://qdnaseq.s3.amazonaws.com/index.html) ("index.html" needs to be included in the request URL, doesn't work without).

I'm busy at Hacker School at the moment, so I'm afraid I can't do much before the release deadline.

**Comment by HenrikBengtsson** [comment]
Thanks.

I understand. An annotation package can wait. Good luck with the Hacker School.

**Comment by daoud-sie** [comment]
I just modified the getBinAnnotation function to also support package datasets. Also added a package QDNAseq.hg19 which I am going to submit to Bioconductor. If you have any comments / suggestions, let me know.
