### ISSUE TITLE
poolRuns colMeans2 error 

### ISSUE THREAD

**Issue by srinew** [ccagc/QDNAseq#83]
This is the error I'm getting when I try to pool multiple normals together.
"Error in colMeans2(oldphenodata, cols = numericCols) : 
  Argument 'x' must be a matrix or a vector."
Is this due to difference in colMeans and colMeans2 functions?

**Comment by HenrikBengtsson** [comment]
matrixStats::colMeans2() does not take data.frame:s, which I guess is what you might have here.
