### ISSUE TITLE
exportBins does log2 transform even on data formats it should not do

### ISSUE THREAD

**Issue by lbeltrame** [ccagc/QDNAseq#88]
Using `exportBins` to export bin calls (`type="calls"`), I was surprised to find a huge number of "-1022" in calls, and no aberration called, even though I knew they were there.

The reason is that `logTransform` is also applied to `calls` when exporting, which produces a completely incorrect output.

**Comment by HenrikBengtsson** [comment]
Thanks for reporting.  I agree that this is an unfortunate default for 'calls'.

**Comment by HenrikBengtsson** [comment]
Thanks for reporting.  I agree that this is an unfortunate default behavior when using `type = "calls".  I think the best would be to ignore `logTransform` whenever `type == "calls"`.  Added do the todo list for next release.

**Comment by HenrikBengtsson** [comment]
This is fixed in **QDNAseq** (>= 1.29.3) that I will push to Bioconductor in the next few days.
