### ISSUE TITLE
Recycling array of length 1 in vector-array arithmetic is deprecated. Use c() or as.vector() instead.

### ISSUE THREAD

**Issue by sxv** [ccagc/QDNAseq#92]
<img width="389" alt="Screen Shot 2021-09-20 at 14 08 44" src="https://user-images.githubusercontent.com/1425091/134052415-1fd6475a-32a6-42a7-9d01-357f863a5c3b.png">

Receiving multiple of this warning. Is this potentially affecting the results? Thanks.

**Comment by HenrikBengtsson** [comment]
Hi, thanks for reporting.  I cannot reproduce this.  Can you please provide the code you're using and your `sessionInfo()`?

PS. Please cut'n'paste output as plain text instead of using screenshots; it makes it easier to search for strings.  Also, screenshorts are not accessible by screen readers.

**Comment by HenrikBengtsson** [comment]
# Reproducible example

These warnings happen when calling `callBins()`.  I can reproduce this using the following minimal example:

```r
library(QDNAseq)
data(LGG150)
data <- LGG150
data <- correctBins(data)
fit <- segmentBins(data)
fit <- callBins(fit)
```

# Troubleshooting

```r
> options(warn = 2L)
TRACKER: Options changed: [n=1] 'warn'.
> fit <- callBins(fit)
EM algorithm started ... 

[1] "Total number of segments present in the data: 62"
[1] "Number of segments used for fitting the model: 24"
Error: Command CGHcall() returned the following error message:
Error in allprior/tot: (converted from warning) Recycling array of length 1 in vector-array arithmetic is deprecated.

 Use c() or as.vector() instead.

Please contact maintainer of package CGHcall: Mark van de Wiel <mark.vdwiel@vumc.nl>

> traceback()
8: stop("Command CGHcall() returned the following error message:\n", 
       e, "Please contact maintainer of package CGHcall: ", maintainer("CGHcall"), 
       call. = FALSE)
7: value[[3L]](cond)
6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
5: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatch({
       suppressVerbose({
           listcall <- CGHcall(seg, organism = organism, ...)
       }, suppress = !verbose)
   }, error = function(e) {
       stop("Command CGHcall() returned the following error message:\n", 
           e, "Please contact maintainer of package CGHcall: ", 
           maintainer("CGHcall"), call. = FALSE)
   })
3: .local(object, organism, method, cutoffs, ...)
2: callBins(fit)
1: callBins(fit)
```

# Conclusion

This is a problem with the [**CGHCall**](http://bioconductor.org/packages/CGHcall/) package.  Other than to

* [ ] report this to https://github.com/tgac-vumc/CGHcall, 

there's nothing we can do about this in **QDNAseq**.

**Comment by HenrikBengtsson** [comment]
Reported to **CGHcall** (https://github.com/tgac-vumc/CGHcall/issues/2).
